const gameTitle = document.getElementById("main-container-title");
const btn1 = document.getElementById("btn1");
const btn2 = document.getElementById("btn2");
const btn3 = document.getElementById("btn3");
const btn4 = document.getElementById("btn4");
const btn5 = document.getElementById("btn5");
const btn6 = document.getElementById("btn6");
const btn7 = document.getElementById("btn7");
const btn8 = document.getElementById("btn8");
const btn9 = document.getElementById("btn9");



let green;
let score = 0;
let gotGreen = false;



const updater = setInterval(() => {
  gameTitle.textContent = `Score: ${score}`;
  
}, 5)



gLoc = Math.floor(Math.random() * 9) + 1;

    switch(gLoc) {
      case 1:
        green = btn1;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 2:
        green = btn2;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 3:
        green = btn3;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 4:
        green = btn4;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 5:
        green = btn5;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 6:
        green = btn6;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 7:
        green = btn7;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;

      case 8:
        green = btn8;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 9:
        green = btn9;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        break;
    }

    green.addEventListener("click", function restart() {
      score++;
      gotGreen = true;
      green.removeEventListener("click", restart);
    })

const game = setInterval(() => {
  if(gotGreen) {
    gLoc = Math.floor(Math.random() * 9) + 1;
    console.log(gLoc);

    switch(gLoc) {
      case 1:
        green = btn1;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 2:
        green = btn2;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 3:
        green = btn3;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 4:
        green = btn4;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 5:
        green = btn5;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 6:
        green = btn6;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 7:
        green = btn7;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;

      case 8:
        green = btn8;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        btn9.textContent = "O";
        btn9.style.backgroundColor = "#f54d3d";
        btn9.style.color = "#ffffff";
        break;
      case 9:
        green = btn9;
        green.textContent = "X";
        green.style.backgroundColor = "#3df58a";
        green.style.color = "#ffffff";
        btn2.textContent = "O";
        btn2.style.backgroundColor = "#f54d3d";
        btn2.style.color = "#ffffff";
        btn3.textContent = "O";
        btn3.style.backgroundColor = "#f54d3d";
        btn3.style.color = "#ffffff";
        btn4.textContent = "O";
        btn4.style.backgroundColor = "#f54d3d";
        btn4.style.color = "#ffffff";
        btn5.textContent = "O";
        btn5.style.backgroundColor = "#f54d3d";
        btn5.style.color = "#ffffff";
        btn6.textContent = "O";
        btn6.style.backgroundColor = "#f54d3d";
        btn6.style.color = "#ffffff";
        btn7.textContent = "O";
        btn7.style.backgroundColor = "#f54d3d";
        btn7.style.color = "#ffffff";
        btn8.textContent = "O";
        btn8.style.backgroundColor = "#f54d3d";
        btn8.style.color = "#ffffff";
        btn1.textContent = "O";
        btn1.style.backgroundColor = "#f54d3d";
        btn1.style.color = "#ffffff";
        break;
    }

    green.addEventListener("click", function restart() {
      score++;
      gotGreen = true;
      green.removeEventListener("click", restart);
    })

    gotGreen = false;
  }
}, 5 )